TASK_STATES={"PLANNED","STARTED","IMPLEMENTED","NEEDS_VERIFICATION","PARTIAL","BLOCKED","FAILED","VERIFIED","COMPLETED","ORPHANED"}
SESSION_STATES={"ACTIVE","IDLE","ENDED","CRASHED","ORPHANED"}
EVIDENCE_LEVELS={"PROPOSED","CODE_CHANGED","EXECUTED","OBSERVED","VERIFIED_E2E","SIDE_EFFECT_INTENT","SIDE_EFFECT_OUTCOME","RECONCILED"}
